= Paybook
Doc Writer <doc.writer@asciidoctor.org>
v1.0, 2014-08-01
:toc: left
:toclevels: 3

== Visão geral

O Paybook é um aplicativo que permite a um usuário criar cobranças para serem enviadas a contatos, acompanhar seu status de pagamento, e posteriormente receber o valor pago.

A operacionalização ocorre por meio de três artefatos básicos: books, cobranças e link de pagamento.

**Book**: é uma coleção de cobranças.
Alguns book permitem definir um conjunto de configurações default para as cobranças cadastradas neles, e outros atuam como gestores das cobranças.

**Cobrança**: é o artefato que permite gerar uma cobrança.
De forma básica, possui um valor, uma data de expiração, e um destinatario.
Uma cobrança pode ter um ou varios links de pagamento.
O link é enviado ao destinatario para que possa realizar seu pagamento.
Quando todos os links de uma cobrança são quitados, a cobrança é dada como 'paga'.

**Link de pagamento**: é o objeto por meio do qual a cobranca é paga.
Toda cobrança possui ao menos um link de pagamento.
Cada link de uma cobrança pode ser considerado uma *parcela*.
Quando o link é pago, a cobrança pode ser encerrada - no caso de cobrança única; ou não - no caso de cobrança parcelada em mais de um link; ou cobrança recorrente, onde os links são gerados de forma periódica.

O caso de uso abaixo apresenta a criação de uma cobrança genérica no aplicativo.

[plantuml,align="center"]
----
include::diagrams/usecase_uso_geral.puml[]
----

O usuário pode ter diversas cobranças cadastradas ao mesmo tempo.
Pode ter quantos books de cobrança desejar, todos do mesmo tipo, ou de tipos diferentes.
O recomendado é que os book sejam organizados por afinidade entre as cobranças.
Por exemplo: um book para cobrança das aulas particulares, outro book para a divisão das despesas dos encontros semanais da turma.

== Estrutura dos documentos

=== Cobrança e links de pagamento

Toda cobrança possui um ou multiplos links de pagamento.
Links de pagamento são armazenados em uma coleção específica, chamada "links".
O documento de link armazena as informações necessarios para gerar uma página de pagamento.
Além disso, possui o id da cobrança pai e o id do destinatário.

[plantuml,align="center"]
----
include::diagrams/cobranca_links.puml[]
----

*valor*: na cobrança é armazenado o valor total que será cobrado.
Os links armazenam o valor de cada parcela do pagamento (no caso de multiplos links) ou o valor total, no caso de um único link.
*vencimento*: na cobrança, diz respeito ao vencimento da mesma.
No caso de uma cobrança com multiplas parcelas, cada link terá uma data de vencimento.
No caso de cobranças periódicas, o vencimento se refere a frequência com que a cobrança gera links para pagamento, onde cada link possuirá uma data especifica de vencimento.
*url*: é a url acessada para realizar o pagamento.
A url é única, e sempre gerada em função dos dados do link de pagamento.
Caso os atributos do link de pagamento sejam alterados, um nova url é gerada.

[plantuml,align="center"]
----
include::diagrams/cobranca_periodica.puml[]
----

No esquema acima, uma cobrança possui seu vencimento todo dia 15. Desta forma, os links são gerados todo mês, com vencimento no dia 15.

=== Pagamento de link e quitação de cobrança

Os links de pagamento seguem o seguinte fluxo de estados:

[plantuml,align="center"]
----
include::diagrams/link_fluxoestados.puml[]
----

Ao pagar o link, a cobranca ao qual ele pertence é notificada para tratar o pagamento.
Caso a cobrança tenha apenas uma parcela, ela é quitada e encerrada.
Caso possua mais de uma parcela, a quitação ocorre apenas quando todas são pagas.
Em caso de cobranças recorrentes, a quitação fica restrita apenas a parcela, mantendo a cobrança como ATIVA.
Para maiores detalhes a respeito do fluxo das cobranças, consultar cada tipo em específico.

== Books e tipos de cobrança

=== 101 - Book simples

Book onde as cobranças são cadastradas de forma individual, de acordo com a necessidade.
Permite as seguintes cobranças:

==== 111 - Cobrança simples

Cobrança que ocorre de forma única com um valor inicialmente definido, uma data de vencimento, e um destinatário.
A cobrança gera um único link de pagamento (para múltiplas parcelas, ver a cobrança <<112 - Cobrança parcelada>>).
Assim que o link é pago, a cobrança fica quitada.
Uma vez quitada, não pode mais ser utilizada.

[plantuml,align="center"]
....
@startuml
skinparam sequenceMessageAlign right
App -> Server : POST charge_id
Server -> App : payment link
@enduml
....

O link possui os mesmos dados da cobrança (valor, destinatario e vencimento).
É possivel posteriormente alterar a cobrança, refletindo em alterações no link de pagamento.

[frame=ends,grid=rows]
[cols="1,1"]
|===
|GET /v1/charges/101/{book_id}/111/
|return all charges of informed book

|GET /v1/charges/101/{book_id}/111/{charge_id}
|return specific charge of informed charge

|POST /v1/charges/101/{book_id}/111/{charge_id}/paylinks
|create payment links for this charge

|PUT /v1/charges/101/{book_id}/111/{charge_id}/paylinks
|update payment links for this charge
|===

==== 112 - Cobrança parcelada

É definido um valor, destinatário e dois ou mais vencimentos.
O valor total é distribuido entre os vencimentos.
A cobrança é quitada assim que todas as parcelas forem pagas.

[plantuml,align="center"]
....
@startuml
package charges {
object charge {
valor: R$300
}
}

package paylinks {
object payment_link_3 {
valor: R$100
vencimento: 05/03/2021
}
object payment_link_2 {
valor: R$100
vencimento: 05/02/2021
}
object payment_link_1 {
valor: R$100
vencimento: 05/01/2021
}
}

charge --> payment_link_1
charge --> payment_link_2
charge --> payment_link_3
@enduml
....

A distribuição do valor total da cobrança entre os links é livre, desde que a soma de todos corresponda ao valor total da cobrança

=== 201 - Book mensalidade

Permite configurar definições gerais como valor e vencimento, para em seguida cadastrar destinatarios que receberão a cobrança

=== 301 - Book mensalidade por uso

Cobrança parte de um valor basico definido (como valor por hora, ou por dia) e para cada destinatario é possivel definir um multiplicados (por exemplo, valor base * 10)

=== 401 - Book divisao de valor

Permite dividir um valor entre os destinatarios cadastrados no book, gerando uma cobranca para cada um.

== Links de pagamento

```
GET /linkpagamento/
{
	"id_link" : "abc123"
}
```

```
PATCH /linkpagamento/
{
	"id_link" : "abc123"
	"op" : "change_status"
	"value" : "novo_status"
}
```

=== Pagamento

O registro de pagamento é feito pelo registro de um pagamento efetuado.
O registro gera um documento na coleção 'pagamentos', e o `id_link` do documento é a chave para identificar o link de pagamento ao qual se refere.

[plantuml,align="center"]
----
include::diagrams/pagamento_link.puml[]
----

```
 REGISTRA PAGAMENTO DE LINK
 PUT /linkspagamento/
 // registra o pagamento de um link. Alem de todos os dados referentes ao pagamento, tem o id_link. desta forma, o server identifica o link que foi pago e consegue realizar os tratamentos necessarios
 { "id_link" : "abc123", dados do pagamento... }
 retorno:
 200 - CREATED
```

== Cancelamento de books e cobranças

O alteração de status para cancelado é feita sempre via APP (ambiente logado).
O server identifica a alteração e executa as ações necessárias.

