@startuml
hide circle
skinparam linetype ortho

entity "Cobranca" as cob {
  *id_cobranca : uid <<generated>>
  --
  *destinatario : Destinatario
  *valor : decimal
}
note right of cob::links
  lista com o id dos links
end note

entity "Destinatario" as dt {
    *id_destinatario
    *nome
    *email
    *telefone
}

cob ||..|| dt
@enduml