@startuml
actor Usuário as user
actor Server as server
actor Pagador as payer

rectangle Paybook {
  usecase "cria book ou utiliza um existente" as UC1
  usecase "cadastra nova cobrança" as UC2
  usecase "gera link de pagamento" as UC3
  usecase "envia link para destinatário" as UC4
  usecase "paga o link" as UC5
  usecase "altera a cobrança para quitada" as UC6
  usecase "notifica o usuário" as UC7
}

user -r- UC1
user -- UC2

server -r- UC3
server -- UC4
server -- UC6
server -- UC7

'payer -l- UC5
UC5 -l- payer

 (UC1) --> (UC2)
 (UC2) --> (UC3)
 (UC3) --> (UC4)
 (UC4) --> (UC5)
 (UC5) --> (UC6)
 (UC6) --> (UC7)

@enduml